export const ROUTES = {
  HOME: "/",
  CATALOGUE: `/catalogue`,
  CATALOGUE_CATEGORY: `/catalogue/category`,
  CANAL_PLUS: "/canalplus",
  SERVICES_CHECKOUT: "/services/checkout",
  SERVICES_STRIPE_PAYMENT_VALIDATION:
    "/services/checkout/:checkoutId/payment/summary",
  SERVICES_THANK_YOU: "/services/thank-you/:orderId",
  CHECKOUT: "/checkout",
  CONTACT: "/contact",
  DASHBOARD: "/dashboard",
  LEGAL_CONDITIONS: "/legal/general-conditions",
  LEGAL_PRIVACY: "/legal/privacy-policy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  PASSWORD_CHANGE: "/accounts/password-change",
  PASSWORD_RESET: "/accounts/password-reset",
  ACCOUNT: "/accounts/profile",
  ABOUT_US: "/about-us",
  ORDERS: "/accounts/orders",
  ACCOUNT_PROFILE: "/accounts/profile",
  DELIVERY_ADDRESS: "/accounts/shipping-address",
  BILLING_ADDRESS: "/accounts/billing-address",
  BENEFICIARY_ADDRESS: "/accounts/beneficiary-address",
  CONTRACT_FORFAIT: "/accounts/telecom-contract",
  HELP_CENTER: "/accounts/help-center",
  LEGAL_NOTICE: "/accounts/legal-notice",
  NOTIFICATION: "/accounts/notification",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SEARCH: "/search",
  PRODUCTS: "/products",
  WISHLIST: "/accounts/wishlist",
  SITEMAP: "/sitemap.xml",
  ROBOTS: "/robots.txt",
  404: "/404",
} as const;
