export const ROUTES = {
  HOME: "/",
  MY_ACCOUNT: "/account",
  VIEW_PROFILE: "/account/profile",
  EDIT_PROFILE: "/account/profile/edit",
  CHANGE_PASSWORD: "/account/settings/change-password",
  SETTINGS: "/account/settings",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  COMMENTS: "/comments",
  POSTS: "/posts",
  FAQ: "/faq",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  CONTACT: "/contact",
  ABOUT: "/about",
  BLOG: "/blog",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SUPPORT: "/support",
  SEARCH: "/search",
  SITEMAP: "/sitemap.xml",
  ROBOTS: "/robots.txt",
  404: "/404",
} as const;
