# .github/workflows/readonly.yml
name: ⛔ Readonly

on:
  pull_request:
    branches:
      - "**" # trigger on all target branches

jobs:
  block:
    name: readonly
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'kit/')
    steps:
      - name: Block merge
        run: |
          echo "❌ kit/* branches are standalone variants"
          echo "❌ They must never be merged into any branch"
          exit 1
